/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb599",
        "surface-container": "#e7eefe",
        "background": "#f9f9ff",
        "tertiary-fixed": "#ffdbce",
        "on-tertiary-fixed": "#370e00",
        "secondary": "#0051d5",
        "on-secondary-fixed": "#00174b",
        "surface-container-highest": "#dce2f3",
        "inverse-primary": "#79db8d",
        "primary": "#00652c",
        "surface-variant": "#dce2f3",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#005323",
        "surface": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fff0ec",
        "on-surface": "#151c27",
        "error-container": "#ffdad6",
        "tertiary-container": "#c34500",
        "surface-tint": "#006d30",
        "on-primary-container": "#d3ffd5",
        "on-primary": "#ffffff",
        "secondary-container": "#316bf3",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e8f8",
        "on-secondary-fixed-variant": "#003ea8",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fefcff",
        "tertiary": "#9a3500",
        "outline-variant": "#becabc",
        "outline": "#6f7a6e",
        "on-surface-variant": "#3f493f",
        "on-primary-fixed": "#00210a",
        "surface-dim": "#d3daea",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#79db8d",
        "primary-container": "#15803d",
        "on-tertiary-fixed-variant": "#7f2b00",
        "surface-bright": "#f9f9ff",
        "on-error": "#ffffff",
        "inverse-surface": "#2a313d",
        "secondary-fixed": "#dbe1ff",
        "on-background": "#151c27",
        "inverse-on-surface": "#ebf1ff",
        "surface-container-low": "#f0f3ff",
        "primary-fixed": "#95f8a7"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
    },
  },
  plugins: [],
}
